### ISSUE TITLE
3 new test failures after upgrading GnuPG from 2.2.30 to 2.2.33

### ISSUE THREAD

**Issue by apteryks** [vsajip/python-gnupg#163]
Hello,

**Describe the bug**
After upgrading GnuPG as per the title on GNU Guix, the test suite fails with the following output:

```
starting phase `check'
..F...F....................F
======================================================================
FAIL: test_encryption_and_decryption (__main__.GPGTestCase)
Test that encryption and decryption works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-gnupg-0.4.8.drv-0/python-gnupg-0.4.8/test_gnupg.py", line 598, in test_encryption_and_decryption
    self.assertEqual(0, result.returncode, "Non-zero return code")
AssertionError: 0 != 2 : Non-zero return code

======================================================================
FAIL: test_get_recipients (__main__.GPGTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-gnupg-0.4.8.drv-0/python-gnupg-0.4.8/test_gnupg.py", line 1260, in test_get_recipients
    self.assertGreater(len(ids), 0)
AssertionError: 0 not greater than 0

======================================================================
FAIL: test_signature_verification (__main__.GPGTestCase)
Test that signing and verification works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-gnupg-0.4.8.drv-0/python-gnupg-0.4.8/test_gnupg.py", line 783, in test_signature_verification
    self.assertEqual(verified.trust_level, verified.TRUST_ULTIMATE)
AssertionError: 0 != 4

----------------------------------------------------------------------
Ran 28 tests in 31.790s

FAILED (failures=3)
error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "python" arguments: ("test_gnupg.py" "--no-doctests") exit-status: 1 term-signal: #f stop-signal: #f> 
phase `check' failed after 31.9 seconds
command "python" "test_gnupg.py" "--no-doctests" failed with status 1
builder for `/gnu/store/glx2pmprrq7r74vaby7hg4jlq3n8pfyf-python-gnupg-0.4.8.drv' failed with exit code 1
```

**Environment**
 - OS, Guix, master branch
 - 0.4.8
 
Attached is the test_gnupg.log file.
[test_gnupg.log](https://github.com/vsajip/python-gnupg/files/7740266/test_gnupg.log)

**Comment by vsajip** [comment]
I can reproduce these failures, but I think this is a regression in GnuPG and needs to be reported there. I'll dig into it.

**Comment by vsajip** [comment]
I've raised this as an issue [upstream](https://dev.gnupg.org/T5742).

**Comment by apteryks** [comment]
Thank you for your investigation and bringing up the issue with upstream!

**Comment by vsajip** [comment]
Note that the tests with GnuPG 2.2.32 and 2.3.3 both succeed, so you can downgrade or upgrade if that's feasible.

**Comment by apteryks** [comment]
Yes, we'll stick with 2.2.32 for now, thank you!
