### ISSUE TITLE
`gpg.verify_file()` throw error when the recv_keys has no public key

### ISSUE THREAD

**Issue by ninyawee** [vsajip/python-gnupg#179]
**Describe the bug**

`gpg.verify_file()` throw error when the recv_keys has no public key.

```
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ben/.local/lib/python3.9/site-packages/gnupg/_meta.py", line 650, in _read_response
    result._handle_status(keyword, value)
  File "/home/ben/.local/lib/python3.9/site-packages/gnupg/_parsers.py", line 1504, in _handle_status
    self.status = '\n'.join([self.status, "key considered"])
TypeError: sequence item 0: expected str instance, NoneType found

```

**To Reproduce**

```python

# this code check signing of `op` 
# https://app-updates.agilebits.com/product_history/CLI2


import gnupg

gpg = gnupg.GPG(homedir=str(Path.home() / '.gnupg'))

key = gpg.recv_keys('3FEF9748469ADBE15DA7CA80AC2D62742012EA22', keyserver='hkps://keyserver.ubuntu.com',)
print(key)

verify = gpg.verify_file(file=str(exe.absolute()), sig_file=str(sig.absolute()))
if verify.status == 'signature valid':
    print("Signature valid")
else:
    print("Signature invalid")
    sys.exit(1)
```

**Expected behavior**

error not thrown

**Environment**
 - OS, including version `Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux`
 - Version of this library `2.3.1`

**Additional information**
Add any other information about the problem here.

**Comment by ninyawee** [comment]
whole code
```python
#!/usr/bin/env python3

# https://app-updates.agilebits.com/product_history/CLI2

import pooch
from pathlib import Path


file_path = pooch.retrieve(
    # URL to one of Pooch's test files
    url="https://cache.agilebits.com/dist/1P/op2/pkg/v2.5.1/op_linux_arm64_v2.5.1.zip",
    known_hash=None
)

print(file_path)


import zipfile

extracted_folder = Path.cwd() / 'temp'
if extracted_folder.exists():
    for file in extracted_folder.iterdir():
        file.unlink()
    extracted_folder.rmdir()

try:
    with zipfile.ZipFile(file_path) as z:
        z.extractall(str(extracted_folder))
except:
    print("Invalid file")

# check gpg signature
# gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
# gpg --verify op.sig
import gnupg
# from fs import open_fs
import sys

sig = extracted_folder / 'op.sig'
exe = extracted_folder / 'op'

gpg = gnupg.GPG(homedir=str(Path.home() / '.gnupg'))
# home_fs = open_fs('.')

key = gpg.recv_keys('3FEF9748469ADBE15DA7CA80AC2D62742012EA22', keyserver='hkps://keyserver.ubuntu.com',)
print(key)

verify = gpg.verify_file(file=str(exe.absolute()), sig_file=str(sig.absolute()))
if verify.status == 'signature valid':
    print("Signature valid")
else:
    print("Signature invalid")
    sys.exit(1)


# add executable permissions
existing_permissions = exe.stat().st_mode
exe.chmod(existing_permissions | 0o100)

# copy to user /.local/bin
target = Path.home() / '.local/bin/op'
import shutil
shutil.copy(exe, target)

# cleanup
extracted_folder.rmdir()
```

**Comment by vsajip** [comment]
Are you sure you're using _this_ library, and not the hostile fork of it by Isis Agora Lovecruft? What exact `pip` command did you use to install this library / how does it appear in e.g. `requirements.txt`? I ask, because _this_ library has no version `2.3.1` - the latest version is `0.4.9`.

**Comment by vsajip** [comment]
I'm closing this as I'm guessing you're using a different, incompatible fork of this library, but you can re-open if that's not the case.
