### ISSUE TITLE
gpg returned an error - return code 2

### ISSUE THREAD

**Issue by tpcgold** [vsajip/python-gnupg#222]
**Describe the bug**
Cannot import keys

**To Reproduce**
import gnupg
gpg = gnupg.GPG(verbose=False)
key_import = gpg.import_keys(gpgfile, passphrase=gpg_pw)

**Environment**
 - Docker Python 3.11 Image
 - python-gnupg 0.5.0
 - gnupg 2.2.27-2+deb11u2

`Traceback (most recent call last):
  File "/app/./main.py", line 192, in <module>
    main()
  File "/app/./main.py", line 151, in main
    gpg.trust_keys(key_import.fingerprints, 'TRUST_ULTIMATE')
  File "/usr/local/lib/python3.11/site-packages/gnupg.py", line 1821, in trust_keys
    raise ValueError('gpg returned an error - return code %d' % p.returncode)
ValueError: gpg returned an error - return code 2`

**Comment by tpcgold** [comment]
Seems like an issue with gnupg but (strange it started with the update of python-gnupg)

verbose:
gpg: Fatal: can't create directory '//.gnupg': Permission denied

maybe there was a default "--no-options" before???
https://linux.die.net/man/1/gpg

----------
update: 

--no-options doesn't fix the issue:
`gpg = gnupg.GPG(verbose=True, options=['--no-options'])`

![image](https://github.com/vsajip/python-gnupg/assets/66625570/13d344f7-4b0c-4bed-a261-322b1906d07b)

will try to create the dict directly in the container image

**Comment by tpcgold** [comment]
for anyone who finds this issue: this solves the issue with GnuPG (this fix wasn't necessary before) - notice this is for unprivileged docker images:
```FROM python:3.11

RUN useradd -u 2000 user
RUN mkdir -p /home/user/.gnupg/

RUN chown user /home/user/.gnupg/
RUN chmod -R 700 /home/user/.gnupg/

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./main.py" ]
