### ISSUE TITLE
[FIXED] AttributeError: 'NoneType' object has no attribute 'groups' ... _match_version_string(version) 

### ISSUE THREAD

**Issue by heksik** [vsajip/python-gnupg#244]
Leaving here if someone will face the same issue after upgrade to Debian 12 bookworm.
If you are getting such error:

`Traceback (most recent call last): ...
  File "/usr/local/lib/python3.13/site-packages/gnupg/gnupg.py", line 162, in __init__
    self.create_trustdb()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/gnupg/gnupg.py", line 172, in create_trustdb
    if self.is_gpg2():
       ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/gnupg/gnupg.py", line 212, in is_gpg2
    return _util._is_gpg2(self.binary_version)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gnupg/_util.py", line 531, in _is_gpg2
    (major, minor, micro) = _match_version_string(version)
                            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gnupg/_util.py", line 617, in _match_version_string
    g = matched.groups()
        ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'
`

You have to change your dockerbuild / CI and replace in pip install from gnupg to **python-gnupg** 0.5.3

**Comment by heksik** [comment]
Closing to not bother project maintainer but please keep this issue visible to help others.

**Comment by vsajip** [comment]
This report is not even relevant for this project. You're using an unmaintained fork of `python-gnupg`. This project does not contain a `_util.py`, nor a method `create_trustdb`.
